### ISSUE TITLE
gvcf only workflow

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#90]
Streamline current [reheader alignment workflow](https://github.com/kids-first/kf-alignment-workflow/blob/master/workflows/kfdrc_cram_reheader_wf.cwl), to skip the reheader process and only output gvcf and related metrics

**Comment by migbro** [comment]
Troubleshooting issues getting the following error while running HC:
```2018-06-25T19:36:11.446562921Z Using GATK jar //gatk-package-4.beta.1-local.jar
2018-06-25T19:36:11.446618626Z Running:
2018-06-25T19:36:11.446627576Z     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Dsnappy.disable=true -Xms2000m -jar //gatk-package-4.beta.1-local.jar PrintReads -R /sbgenomics/Projects/ef708ec3-5606-47dc-812f-b4c977e69959/Homo_sapiens_assembly38.fasta -I /sbgenomics/Projects/ef708ec3-5606-47dc-812f-b4c977e69959/BS_1G9N4SVD.cram --interval_padding 500 -L /sbgenomics/workspaces/ef708ec3-5606-47dc-812f-b4c977e69959/tasks/0d5f64a1-f6a9-4634-b20c-9a0838ab3bd0/root_picard_intervallisttools/temp_0019_of_50/scattered.interval_list -O local.sharded.cram
2018-06-25T19:36:14.028458761Z [June 25, 2018 7:36:13 PM GMT] PrintReads  --output local.sharded.cram --intervals /sbgenomics/workspaces/ef708ec3-5606-47dc-812f-b4c977e69959/tasks/0d5f64a1-f6a9-4634-b20c-9a0838ab3bd0/root_picard_intervallisttools/temp_0019_of_50/scattered.interval_list --interval_padding 500 --input /sbgenomics/Projects/ef708ec3-5606-47dc-812f-b4c977e69959/BS_1G9N4SVD.cram --reference /sbgenomics/Projects/ef708ec3-5606-47dc-812f-b4c977e69959/Homo_sapiens_assembly38.fasta  --interval_set_rule UNION --interval_exclusion_padding 0 --readValidationStringency SILENT --secondsBetweenProgressUpdates 10.0 --disableSequenceDictionaryValidation false --createOutputBamIndex true --createOutputBamMD5 false --createOutputVariantIndex true --createOutputVariantMD5 false --lenient false --addOutputSAMProgramRecord true --addOutputVCFCommandLine true --cloudPrefetchBuffer 40 --cloudIndexPrefetchBuffer -1 --disableBamIndexCaching false --help false --version false --showHidden false --verbosity INFO --QUIET false --use_jdk_deflater false --use_jdk_inflater false --disableToolDefaultReadFilters false
2018-06-25T19:36:14.028716946Z [June 25, 2018 7:36:13 PM GMT] Executing as root@95ada78c9495 on Linux 4.4.0-1052-aws amd64; OpenJDK 64-Bit Server VM 1.8.0_131-b11; Version: 4.beta.1
2018-06-25T19:36:21.159632994Z ERROR	2018-06-25 19:36:21	Slice	Reference MD5 mismatch for slice 5:57337422-76107931, ACACCACACC...ATTTGCATAT
2018-06-25T19:36:21.968332395Z [June 25, 2018 7:36:21 PM GMT] org.broadinstitute.hellbender.tools.PrintReads done. Elapsed time: 0.13 minutes.
2018-06-25T19:36:21.968353943Z Runtime.totalMemory()=2474639360
2018-06-25T19:36:21.969186952Z htsjdk.samtools.cram.CRAMException: Reference sequence MD5 mismatch for slice: sequence id 5, start 57337422, span 18770510, expected MD5 3da50b6189a0e2277b94e9e78795ff61
2018-06-25T19:36:21.969383310Z 	at htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:187)
2018-06-25T19:36:21.969391705Z 	at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:261)
2018-06-25T19:36:21.969396196Z 	at htsjdk.samtools.CRAMFileReader$CRAMIntervalIterator.getNextRecord(CRAMFileReader.java:531)
2018-06-25T19:36:21.969449498Z 	at htsjdk.samtools.CRAMFileReader$CRAMIntervalIterator.next(CRAMFileReader.java:525)
2018-06-25T19:36:21.969468323Z 	at htsjdk.samtools.CRAMFileReader$CRAMIntervalIterator.next(CRAMFileReader.java:469)
2018-06-25T19:36:21.969475597Z 	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:576)
2018-06-25T19:36:21.969483813Z 	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
2018-06-25T19:36:21.969490483Z 	at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.loadNextRecord(SamReaderQueryingIterator.java:114)
2018-06-25T19:36:21.969497140Z 	at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:151)
2018-06-25T19:36:21.969506520Z 	at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:29)
2018-06-25T19:36:21.969513200Z 	at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:29)
2018-06-25T19:36:21.969519705Z 	at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:15)
2018-06-25T19:36:21.969528180Z 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
2018-06-25T19:36:21.969534650Z 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
2018-06-25T19:36:21.969541089Z 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
2018-06-25T19:36:21.969548274Z 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
2018-06-25T19:36:21.969646073Z 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
2018-06-25T19:36:21.969655500Z 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
2018-06-25T19:36:21.969696639Z 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2018-06-25T19:36:21.969707794Z 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
2018-06-25T19:36:21.969714312Z 	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:94)
2018-06-25T19:36:21.969731989Z 	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:838)
2018-06-25T19:36:21.969741306Z 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:115)
2018-06-25T19:36:21.969747831Z 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
2018-06-25T19:36:21.969754134Z 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
2018-06-25T19:36:21.969765576Z 	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
2018-06-25T19:36:21.969773958Z 	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
2018-06-25T19:36:21.969779751Z 	at org.broadinstitute.hellbender.Main.main(Main.java:230)
```
Trying newer version of gatk in kfdrc docker

**Comment by migbro** [comment]
Needs upload to github, for now can be found here:
```https://cavatica.sbgenomics.com/u/brownm28/kf-gvcf-only-pipe/```
1) Using gatk v4.0.3.0 from current docker resolved issues with reading crams, options had to be updated to be compatible.
2) picard renamesampleinbvcf tool used to reheader vcf output from mergevcfs
3) added biospecimen name input for reheader of vcf
4) no verify bam version has added contamination float as input

**Comment by migbro** [comment]
Final product has been pushed to:
```https://github.com/kids-first/kf-alignment-workflow/tree/update/gvcf-only-by-mb```

**Comment by yuankunzhu** [comment]
cat you invite me to your cavatica testing project? https://cavatica.sbgenomics.com/u/brownm28/kf-gvcf-only-pipe/? @migbro

**Comment by yuankunzhu** [comment]
great work. close this ticket.
